name: ums
services:
  frontend-dev:
    image: node:19-alpine
    volumes:
      - "./frontend:/home/node/app"
    ports:
      - 3000:3000
    working_dir: /home/node/app
    profiles:
      - dev
    entrypoint: ["npm", "run", "dev"]
    depends_on:
      - backend-dev

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    profiles:
      - prod

  backend-dev:
    build: ./backend
    volumes:
      - "./backend:/home/node/app:ro"
    entrypoint: "npm run dev"
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
    profiles:
      - dev
    depends_on:
      - db

  backend:
    build: ./backend
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
    profiles:
      - prod
    depends_on:
      - db

  nginx-dev:
    image: nginx:1.23.4-alpine
    volumes:
      - "./nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "80:80"
    depends_on:
      - frontend-dev
      - backend-dev
    profiles:
      - dev

  db:
    image: postgres:15
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: supersecretpasswordplsdontsteal

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  db-data:
